# Generated by Django 5.1.4 on 2025-03-13 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Pandit_app', '0003_pandit_email_id'),
        ('user_app', '0003_rename_user_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Phone_no', models.IntegerField()),
                ('Date', models.DateField()),
                ('Work', models.CharField(max_length=50)),
                ('Status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('Pandit_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pandit_app.pandit')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.user_table')),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
    ]
