# Generated by Django 5.1.4 on 2025-03-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Email_Id',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
