# Generated by Django 5.1.4 on 2025-03-05 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pandit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pandit',
            table='Pandit',
        ),
    ]
