# Generated by Django 5.1.4 on 2025-03-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pandit_app', '0002_alter_pandit_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='pandit',
            name='Email_Id',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
